# Generated by Django 2.2.3 on 2019-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=20)),
            ],
        ),
    ]
