# Generated by Django 2.2.3 on 2019-10-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='num_projects',
        ),
    ]
