# Generated by Django 2.2.3 on 2019-10-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0003_remove_userprofile_num_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
