# Generated by Django 2.2.3 on 2019-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0004_userprofile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.CharField(default='', max_length=1000000, null=True),
        ),
    ]
