# Generated by Django 2.2.3 on 2019-10-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0006_auto_20191013_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='due',
            new_name='due_date',
        ),
    ]
