# Generated by Django 2.2.3 on 2019-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator_app', '0009_auto_20191013_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
